-- ==============================================================================
-- TEENSPACE 2026: SUPABASE TRASH / RECYCLE BIN TABLE SETUP
-- Run this script in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.trash (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deleted_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    deleted_by TEXT,
    item_type TEXT NOT NULL, -- 'student' (from directory) or 'donated_contact' (from donated list)
    reg_id TEXT,
    name TEXT,
    phone TEXT,
    parent_phone TEXT,
    student_class TEXT,
    school TEXT,
    place TEXT,
    panchayath TEXT,
    ward TEXT,
    unit TEXT,
    zone TEXT,
    assigned_vehicle TEXT,
    pickup_order INTEGER,
    picked_up BOOLEAN DEFAULT false,
    original_timestamp TIMESTAMPTZ,
    raw_data JSONB
);

-- Optimize queries by deleted_at, item_type and reg_id
CREATE INDEX IF NOT EXISTS idx_trash_deleted_at ON public.trash(deleted_at DESC);
CREATE INDEX IF NOT EXISTS idx_trash_item_type ON public.trash(item_type);
CREATE INDEX IF NOT EXISTS idx_trash_reg_id ON public.trash(reg_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.trash ENABLE ROW LEVEL SECURITY;

-- Create policies for anon access (so frontend admin portal can read, insert, restore, and purge)
DO $$
BEGIN
    DROP POLICY IF EXISTS "Allow anon select on trash" ON public.trash;
    DROP POLICY IF EXISTS "Allow anon insert on trash" ON public.trash;
    DROP POLICY IF EXISTS "Allow anon update on trash" ON public.trash;
    DROP POLICY IF EXISTS "Allow anon delete on trash" ON public.trash;

    CREATE POLICY "Allow anon select on trash" ON public.trash FOR SELECT TO anon USING (true);
    CREATE POLICY "Allow anon insert on trash" ON public.trash FOR INSERT TO anon WITH CHECK (true);
    CREATE POLICY "Allow anon update on trash" ON public.trash FOR UPDATE TO anon USING (true) WITH CHECK (true);
    CREATE POLICY "Allow anon delete on trash" ON public.trash FOR DELETE TO anon USING (true);
END $$;
